spring:
  thymeleaf:
   cache: false
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
